[package]
name = "atomic_swap_tuna"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }

[addresses]
FACoin = "0x6e95f71f9b976cf57b1109bdd287146e94e88ed098dae22ad78786f241bc3156"
AtomicSwapTuna = "0x6e95f71f9b976cf57b1109bdd287146e94e88ed098dae22ad78786f241bc3156"

[dev-dependencies]
